version: "1"
projects:
- name: signal canary
  environments:
  - name: Production
    services:
    - type: keyvalue
      name: osint-queue
      plan: free
      region: singapore
      maxmemoryPolicy: volatile-ttl
      ipAllowList:
      - source: 0.0.0.0/0

    - type: web
      name: umami
      env: docker
      repo: https://github.com/thomascenni/umami.git
      branch: main
      plan: free
      region: singapore
      envVars:
        - key: DATABASE_URL
          fromDatabase:
            name: umami-db
            property: connectionString
        - key: HASH_SALT
          generateValue: true
        - key: REDIS_URL
          fromService:
            type: keyvalue
            name: osint-queue
            property: connectionString

    databases:
    - name: umami-db
      plan: free
      databaseName: umami
      user: umami
      region: singapore